version: "3"

services: 
    bscexplorer: 
        build: .
        container_name: explorer
        networks:
            net_151_net0:
                ipv4_address: 10.151.0.71
        volumes: 
            - ./bsc-node/explorer:/root/.ethereum
        ports: 
            - 8545:8545
            - 30303:30303
